# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Fisher Lebo
description:      '<a href="https://twitter.com/fisher_lebo" target="_blank">@fisher_lebo</a>.'
url:              http://fisher-lebo.github.io
paginate:         5
baseurl:          /
author:
  name:           Fisher Lebo
  url:            https://twitter.com/fisher-lebo
  email:          fisher.lebo@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/fisher-lebo/fisher-lebo.github.io
