# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Fisher Lebo
tagline:          go fish
url:              http://fisher-lebo.github.io
paginate:         1
baseurl:          /
author:
  name:           Fisher Lebo
  url:            https://twitter.com/fisher-lebo
  email:          fisher.lebo@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/fisher-lebo/fisher-lebo.github.io
