# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron Lebo
description:      '<a href="https://twitter.com/aaron_lebo" target="_blank">@aaron_lebo</a>'
url:              http://aaron-lebo.github.io
paginate:         5
baseurl:          /
author:
  name:           Aaron Lebo
  url:            https://twitter.com/aaron_lebo
  email:          aaron.matthew.lebo@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/aaron-lebo/aaron-lebo.github.io
